### ISSUE TITLE
Creating a new PR comment thread fails with "An author of a comment cannot be updated."

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/azure-devops-node-api#173] opened 2018-04-12 18:55 UTC
1. Please check our current Issues to see if someone already reported this https://github.com/Microsoft/vsts-node-api/issues
2. Take a look at our Instructions for logging issues https://github.com/Microsoft/vsts-node-api/blob/master/CONTRIBUTING.md#instructions-for-logging-issues

### Environment
**Node version**: 8.3.0
**Npm version**: 5.8.0
**OS and version**: Windows 10
**vsts-node-api version**: 6.5.0
**TFS Version**: Microsoft Visual Studio Team Foundation Server Version 16.122.27409.2

### Issue Description
I am writing a tool that will add a comment on certain lines of code in a PR.  While playing with the API I noticed that I must use `gitApi.createThread` and pass in some (IMO) incredibly verbose options.  Here's a snippet of what I'm doing:

```ts
const commentAuthor = this.allIdentityRefs.find((id: IdentityRef) => id.uniqueName === this.opts.usernamePrefix + username);
const mostRecentIterationId = this.prIterations[this.prIterations.length - 1].id;

const thread: GitPullRequestCommentThread = {
    _links: {},
    comments: [{
        _links: {},
        author: commentAuthor,
        commentType: CommentType.CodeChange,
        content: 'Test comment!',
        id: 1,
        isDeleted: false,
        lastContentUpdatedDate: new Date(),
        lastUpdatedDate: new Date(),
        parentCommentId: 0,
        publishedDate: new Date(),
        usersLiked: []
    }],
    id: 0,
    isDeleted: false,
    lastUpdatedDate: new Date(),
    properties: {},
    publishedDate: new Date(),
    status: CommentThreadStatus.Active,
    threadContext: {
        filePath,
        leftFileEnd: end,
        leftFileStart: start,
        rightFileEnd: end,
        rightFileStart: start
    },
    pullRequestThreadContext: {
        changeTrackingId: mostRecentIterationId,
        iterationContext: {
            firstComparingIteration: mostRecentIterationId,
            secondComparingIteration: mostRecentIterationId
        },
        trackingCriteria: {
            firstComparingIteration: mostRecentIterationId,
            origFilePath: filePath,
            origLeftFileEnd: end,
            origLeftFileStart: start,
            origRightFileEnd: end,
            origRightFileStart: start,
            secondComparingIteration: mostRecentIterationId
        }
    }
};

this.gitApi.createThread(thread, this.pullRequest.repository.id, this.pullRequest.pullRequestId)
    .then((newThread: GitPullRequestCommentThread) => {
        console.log(newThread);
        resolve();
    })
    .catch((err: string) => {
        console.error('createThread', err);
        reject(err);
    });
```

### Expected behaviour
I'd expect it to work and create the comment thread in the PR.

### Actual behaviour
Instead, the promise fails and I get this error:
```
(node:32988) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: An author of a comment cannot be updated.
Parameter name: Author
```

I am creating a new comment thread, not updating an existing one. None of the properties in the typedefs are marked as being optional, so apparently 100% of these are required, and then it scolds me for doing this.  I have no idea what I'm supposed to do at this point.

### Steps to reproduce
1. call `gitApi.createThread` and fill in all the required parameters

### Temp workaround
The issue seems to be that all properties are marked as being required, but removing some of them and forcing/coercing the `any` type on my `Comment` object and omitting the `author` property **DOES** work and a comment thread is created on the PR!

**Comment by stephenmichaelf** [comment] 2018-04-12 19:59
Thanks for letting us know @chrismbarr.

From what I see there are two issues:
1. Fields are marked as required that aren't
2. When creating a thread you get the author cannot be updated error

Is that accurate?

**Comment by chrismbarr** [comment] 2018-04-13 11:40
I tried marking my objects as `any` and then deleting as many fields as I could with it still working.  This seems to be the minimal number of fields needed to create a new comment thread:
```ts
//This rule needs to be disabled because of a TFS issue and we have to coerce the type and remove some properties: https://github.com/Microsoft/vsts-node-api/issues/173
// tslint:disable:no-any
const comment: any = {
    commentType: CommentType.CodeChange,
    content: commentText
};

const mostRecentIterationId = this.prIterations[this.prIterations.length - 1].id;
//Similar to GitPullRequestCommentThread
const thread: any = {
    comments: [comment],
    lastUpdatedDate: new Date(),
    publishedDate: new Date(),
    status: CommentThreadStatus.Active,
    threadContext: {
        filePath,
        rightFileEnd: end,
        rightFileStart: start
    },
    pullRequestThreadContext: {
        changeTrackingId: mostRecentIterationId,
        iterationContext: {
            firstComparingIteration: mostRecentIterationId,
            secondComparingIteration: mostRecentIterationId
        },
        trackingCriteria: {
            firstComparingIteration: mostRecentIterationId,
            origFilePath: filePath,
            origRightFileEnd: end,
            origRightFileStart: start,
            secondComparingIteration: mostRecentIterationId
        }
    }
};
// tslint:enable:no-any

this.gitApi.createThread(thread, this.pullRequest.repository.id, this.pullRequest.pullRequestId)
    .then(() => resolve)
    .catch((err: string) => {
        console.error('createThread', err);
        reject(err);
    });
```

**Comment by stephenmichaelf** [comment] 2018-04-13 12:49
Thanks for the clarification. The APIs in this library are generated so that is part of the problem. I am going to take a deeper look into the upstream generation and see if we can accurately mark properties as optional. I agree this is bad UX and very confusing. We have had several people mention this.

I will update you once I know more.

You are not blocked, correct?

Thanks again for bringing this up and taking the time to provide details.

**Comment by chrismbarr** [comment] 2018-04-13 14:15
cool thanks!  No, I'm not blocked, just forced to now use weaker types, which I don't love, but oh well!

A possible solution to this might be to have 2 versions of each object type.  One marked with optional properties for when you are sending an object in a request, and another one with non-optional properties for when you are receiving the object back from a response.  Having the properties marked as "possibly undefined" on a response would introduce a lot of annoying & unnecessary null checks.

**Comment by damccorm** [comment] 2018-09-28 19:31
I think requiring the author to be omitted is actually the correct behavior - you shouldn't be allowed to create a comment for other people, so I think the comments are automatically set to have the caller be the author which makes sense to me. Setting someone else as the author, then, would end up trying to reassign the comment to a different author, causing an error.

Regarding the optional properties, that is being tracked in #74. Since the issue is being tracked there, I'm going to close here, feel free to reopen if appropriate or follow up further in that thread though.

**Closed by damccorm** 2018-09-28 19:31 UTC
Labels: enhancement, git

**Comment by czechdude** [comment] 2021-11-05 14:13
> I think requiring the author to be omitted is actually the correct behavior - you shouldn't be allowed to create a comment for other people, so I think the comments are automatically set to have the caller be the author which makes sense to me. Setting someone else as the author, then, would end up trying to reassign the comment to a different author, causing an error.

Hello, regarding the author being reassigned, I would be very welcome, if that would be possible, because I'm migrating organisations by writing migration scripts and when I migrate Git commit comments (undocumented! but I assume same code behind) I can be the only author, in opposite the Work Item migration can be done impersonated to any author with just a string with the name of the author and the AD connects the name with the user. There is this "via":

![image](https://user-images.githubusercontent.com/601761/140524080-c0b0ce11-9565-4d06-9956-c9799e0944f3.png)

Thanks for your consideration.
