### ISSUE TITLE
Proxy should work when password has url sensitive characters.

### ISSUE THREAD

**Issue by omeshp** [Microsoft/azure-devops-node-api#132] opened 2017-12-20 11:31 UTC
Currently typed-rest-client has bug where proxy doesn't work if password has url sensitive characters (https://github.com/Microsoft/typed-rest-client/issues/49), 
Once the issue is fixed in typed-rest-client we should consume the appropriate version for vsts-node-api.

**Comment by bryanmacfarlane** [comment] 2018-01-17 22:23
@stephenmichaelf - just need to consume the new typed rest client.

**Comment by damccorm** [comment] 2018-09-28 18:36
I'm going to go ahead and close this since we updated to the latest typed-rest-client and it is confirmed working there. Feel free to reopen if appropriate.

**Closed by damccorm** 2018-09-28 18:36 UTC
Labels: enhancement

**Comment by omeshp** [comment] 2018-09-28 20:04
@damccorm @stephenmichaelf Thanks for taking care of this. I haven't gotten around to trying this yet, will update once I do. You can close the issue for now.
